package ProjetCorbaDNS;

/**
* ProjetCorbaDNS/ClientIDHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/Users/Manavai/workspace/ProjetCorba-DNS/GestionNomsDomaine.idl
* vendredi 16 décembre 2016 18 h 25 CET
*/

public final class ClientIDHolder implements org.omg.CORBA.portable.Streamable
{
  public ProjetCorbaDNS.ClientID value = null;

  public ClientIDHolder ()
  {
  }

  public ClientIDHolder (ProjetCorbaDNS.ClientID initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ProjetCorbaDNS.ClientIDHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ProjetCorbaDNS.ClientIDHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ProjetCorbaDNS.ClientIDHelper.type ();
  }

}
