package ProjetCorbaDNS;

/**
* ProjetCorbaDNS/DomainNameParametersHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/Users/Manavai/workspace/ProjetCorba-DNS/GestionNomsDomaine.idl
* vendredi 16 décembre 2016 18 h 25 CET
*/

public final class DomainNameParametersHolder implements org.omg.CORBA.portable.Streamable
{
  public ProjetCorbaDNS.DomainNameParameters value = null;

  public DomainNameParametersHolder ()
  {
  }

  public DomainNameParametersHolder (ProjetCorbaDNS.DomainNameParameters initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ProjetCorbaDNS.DomainNameParametersHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ProjetCorbaDNS.DomainNameParametersHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ProjetCorbaDNS.DomainNameParametersHelper.type ();
  }

}
