package ProjetCorbaDNS;

/**
* ProjetCorbaDNS/DomainNameInformationsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/Users/Manavai/workspace/ProjetCorba-DNS/GestionNomsDomaine.idl
* vendredi 16 décembre 2016 18 h 25 CET
*/

public final class DomainNameInformationsHolder implements org.omg.CORBA.portable.Streamable
{
  public ProjetCorbaDNS.DomainNameInformations value = null;

  public DomainNameInformationsHolder ()
  {
  }

  public DomainNameInformationsHolder (ProjetCorbaDNS.DomainNameInformations initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ProjetCorbaDNS.DomainNameInformationsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ProjetCorbaDNS.DomainNameInformationsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ProjetCorbaDNS.DomainNameInformationsHelper.type ();
  }

}
