package ProjetCorbaDNS;


/**
* ProjetCorbaDNS/DomainNameParameters.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/Users/Manavai/workspace/ProjetCorba-DNS/GestionNomsDomaine.idl
* vendredi 16 décembre 2016 18 h 25 CET
*/

public final class DomainNameParameters implements org.omg.CORBA.portable.IDLEntity
{

  // non-dÃ©fini
  public String ParameterType = null;
  public String ParameterValue = null;

  public DomainNameParameters ()
  {
  } // ctor

  public DomainNameParameters (String _ParameterType, String _ParameterValue)
  {
    ParameterType = _ParameterType;
    ParameterValue = _ParameterValue;
  } // ctor

} // class DomainNameParameters
