package ProjetCorbaDNS;


/**
* ProjetCorbaDNS/DomainNameInformationsHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/Users/Manavai/workspace/ProjetCorba-DNS/GestionNomsDomaine.idl
* vendredi 16 décembre 2016 18 h 25 CET
*/

abstract public class DomainNameInformationsHelper
{
  private static String  _id = "IDL:ProjetCorbaDNS/DomainNameInformations:1.0";

  public static void insert (org.omg.CORBA.Any a, ProjetCorbaDNS.DomainNameInformations that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ProjetCorbaDNS.DomainNameInformations extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [4];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (ProjetCorbaDNS.DomainNameHelper.id (), "DomainName", _tcOf_members0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "domainName",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (ProjetCorbaDNS.IPAddressHelper.id (), "IPAddress", _tcOf_members0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "IPAddr",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (ProjetCorbaDNS.ClientUIDHelper.id (), "ClientUID", _tcOf_members0);
          _members0[2] = new org.omg.CORBA.StructMember (
            "clientUID",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (ProjetCorbaDNS.DateHelper.id (), "Date", _tcOf_members0);
          _members0[3] = new org.omg.CORBA.StructMember (
            "ExpirationDate",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (ProjetCorbaDNS.DomainNameInformationsHelper.id (), "DomainNameInformations", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ProjetCorbaDNS.DomainNameInformations read (org.omg.CORBA.portable.InputStream istream)
  {
    ProjetCorbaDNS.DomainNameInformations value = new ProjetCorbaDNS.DomainNameInformations ();
    value.domainName = istream.read_string ();
    value.IPAddr = istream.read_string ();
    value.clientUID = istream.read_string ();
    value.ExpirationDate = istream.read_string ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ProjetCorbaDNS.DomainNameInformations value)
  {
    ostream.write_string (value.domainName);
    ostream.write_string (value.IPAddr);
    ostream.write_string (value.clientUID);
    ostream.write_string (value.ExpirationDate);
  }

}
