package ProjetCorbaDNS;


/**
* ProjetCorbaDNS/RegistrarClass.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/Users/Manavai/workspace/ProjetCorba-DNS/GestionNomsDomaine.idl
* vendredi 16 décembre 2016 18 h 25 CET
*/

public final class RegistrarClass implements org.omg.CORBA.portable.IDLEntity
{
  public String Nom = null;
  public String Contact = null;
  public String RIB = null;

  public RegistrarClass ()
  {
  } // ctor

  public RegistrarClass (String _Nom, String _Contact, String _RIB)
  {
    Nom = _Nom;
    Contact = _Contact;
    RIB = _RIB;
  } // ctor

} // class RegistrarClass
