package ProjetCorbaDNS;


/**
* ProjetCorbaDNS/RegistrarListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/Users/Manavai/workspace/ProjetCorba-DNS/GestionNomsDomaine.idl
* vendredi 16 décembre 2016 18 h 25 CET
*/


//
public final class RegistrarListHolder implements org.omg.CORBA.portable.Streamable
{
  public ProjetCorbaDNS.RegistrarClass value[] = null;

  public RegistrarListHolder ()
  {
  }

  public RegistrarListHolder (ProjetCorbaDNS.RegistrarClass[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ProjetCorbaDNS.RegistrarListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ProjetCorbaDNS.RegistrarListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ProjetCorbaDNS.RegistrarListHelper.type ();
  }

}
