package ProjetCorbaDNS;


/**
* ProjetCorbaDNS/RegistrarListHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/Users/Manavai/workspace/ProjetCorba-DNS/GestionNomsDomaine.idl
* vendredi 16 décembre 2016 18 h 25 CET
*/


//
abstract public class RegistrarListHelper
{
  private static String  _id = "IDL:ProjetCorbaDNS/RegistrarList:1.0";

  public static void insert (org.omg.CORBA.Any a, ProjetCorbaDNS.RegistrarClass[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ProjetCorbaDNS.RegistrarClass[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = ProjetCorbaDNS.RegistrarClassHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (ProjetCorbaDNS.RegistrarListHelper.id (), "RegistrarList", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ProjetCorbaDNS.RegistrarClass[] read (org.omg.CORBA.portable.InputStream istream)
  {
    ProjetCorbaDNS.RegistrarClass value[] = null;
    int _len0 = istream.read_long ();
    value = new ProjetCorbaDNS.RegistrarClass[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = ProjetCorbaDNS.RegistrarClassHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ProjetCorbaDNS.RegistrarClass[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      ProjetCorbaDNS.RegistrarClassHelper.write (ostream, value[_i0]);
  }

}
