package ProjetCorbaDNS.ServeurDNS;

/**
* ProjetCorbaDNS/ServeurDNS/DNSresolutionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/Users/Manavai/workspace/ProjetCorba-DNS/GestionNomsDomaine.idl
* vendredi 16 décembre 2016 18 h 25 CET
*/


//
public final class DNSresolutionHolder implements org.omg.CORBA.portable.Streamable
{
  public ProjetCorbaDNS.ServeurDNS.DNSresolution value = null;

  public DNSresolutionHolder ()
  {
  }

  public DNSresolutionHolder (ProjetCorbaDNS.ServeurDNS.DNSresolution initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ProjetCorbaDNS.ServeurDNS.DNSresolutionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ProjetCorbaDNS.ServeurDNS.DNSresolutionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ProjetCorbaDNS.ServeurDNS.DNSresolutionHelper.type ();
  }

}
