package ProjetCorbaDNS.ServeurDNS;


/**
* ProjetCorbaDNS/ServeurDNS/DNSServForRegistrarOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/Users/Manavai/workspace/ProjetCorba-DNS/GestionNomsDomaine.idl
* vendredi 16 d�cembre 2016 18 h 25 CET
*/


//
public interface DNSServForRegistrarOperations 
{

  // vérifier l'état d'un nom de domaine (libre ou non)
  boolean IsDomainNameFree (String DomainName);

  // Ajout et supression de nom de domaine
  boolean AddDomainName (ProjetCorbaDNS.DomainNameInformations DomainNameInformations);
  boolean DelDomainName (ProjetCorbaDNS.DomainNameInformations DomainNameInformations);

  // Vérification de la date d'expiration
  String CheckDomainExpiryDate (String DomainNameToRenew);

  // Renouvellement d'un nom de domaine
  boolean ExtendDomainNameRent (ProjetCorbaDNS.DomainNameInformations DomainNameInformations, int NumberOfYears);

  // Changement de propriétaire d'un nom de domaine
  boolean ApplyOwnerChangement (ProjetCorbaDNS.UserInformations NewOwner, ProjetCorbaDNS.UserInformations OldOwner);
} // interface DNSServForRegistrarOperations
