package ProjetCorbaDNS.Delegataire;


/**
* ProjetCorbaDNS/Delegataire/DelegataireForDNSServ.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/Users/Manavai/workspace/ProjetCorba-DNS/GestionNomsDomaine.idl
* vendredi 16 décembre 2016 18 h 25 CET
*/


//
public interface DelegataireForDNSServ extends DelegataireForDNSServOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface DelegataireForDNSServ
