package ProjetCorbaDNS.Delegataire;


/**
* ProjetCorbaDNS/Delegataire/DelegataireForClientOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/Users/Manavai/workspace/ProjetCorba-DNS/GestionNomsDomaine.idl
* vendredi 16 d�cembre 2016 18 h 25 CET
*/


//
public interface DelegataireForClientOperations 
{

  // méthode pour obtenir la liste des registrar pour un nom de domaine donné pour un changement de registrar
  ProjetCorbaDNS.RegistrarClass[] DomainNameChangeRegistrarRequest (String DomainName);
} // interface DelegataireForClientOperations
