package ProjetCorbaDNS.Delegataire;


/**
* ProjetCorbaDNS/Delegataire/DelegataireForDNSServOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/Users/Manavai/workspace/ProjetCorba-DNS/GestionNomsDomaine.idl
* vendredi 16 d�cembre 2016 18 h 25 CET
*/


//
public interface DelegataireForDNSServOperations 
{

  // résolution DNS
  String resolVDomainName (String DomainName);

  // résolution WhoIS
  String WhoIs (String IPAddress);
} // interface DelegataireForDNSServOperations
