package ProjetCorbaDNS.Delegataire;

/**
* ProjetCorbaDNS/Delegataire/DelegataireForProprietaireHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/Users/Manavai/workspace/ProjetCorba-DNS/GestionNomsDomaine.idl
* vendredi 16 décembre 2016 18 h 25 CET
*/


//
public final class DelegataireForProprietaireHolder implements org.omg.CORBA.portable.Streamable
{
  public ProjetCorbaDNS.Delegataire.DelegataireForProprietaire value = null;

  public DelegataireForProprietaireHolder ()
  {
  }

  public DelegataireForProprietaireHolder (ProjetCorbaDNS.Delegataire.DelegataireForProprietaire initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ProjetCorbaDNS.Delegataire.DelegataireForProprietaireHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ProjetCorbaDNS.Delegataire.DelegataireForProprietaireHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ProjetCorbaDNS.Delegataire.DelegataireForProprietaireHelper.type ();
  }

}
