package ProjetCorbaDNS.Proprietaire;


/**
* ProjetCorbaDNS/Proprietaire/_ProprietaireforRegistrarStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/Users/Manavai/workspace/ProjetCorba-DNS/GestionNomsDomaine.idl
* vendredi 16 décembre 2016 18 h 25 CET
*/

public class _ProprietaireforRegistrarStub extends org.omg.CORBA.portable.ObjectImpl implements ProjetCorbaDNS.Proprietaire.ProprietaireforRegistrar
{


  // notifie le client qu'un nom de domaine est sur le point d'expirer
  public void DomainNameExpiration (String DomainName, String DateExpiration)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("DomainNameExpiration", false);
                ProjetCorbaDNS.DomainNameHelper.write ($out, DomainName);
                ProjetCorbaDNS.DateHelper.write ($out, DateExpiration);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                DomainNameExpiration (DomainName, DateExpiration        );
            } finally {
                _releaseReply ($in);
            }
  } // DomainNameExpiration

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ProjetCorbaDNS/Proprietaire/ProprietaireforRegistrar:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _ProprietaireforRegistrarStub
