package ProjetCorbaDNS.Proprietaire;


/**
* ProjetCorbaDNS/Proprietaire/ProprietaireforRegistrar.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/Users/Manavai/workspace/ProjetCorba-DNS/GestionNomsDomaine.idl
* vendredi 16 décembre 2016 18 h 25 CET
*/

public interface ProprietaireforRegistrar extends ProprietaireforRegistrarOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ProprietaireforRegistrar
