package ProjetCorbaDNS.Proprietaire;


/**
* ProjetCorbaDNS/Proprietaire/ProprietaireforRegistrarOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/Users/Manavai/workspace/ProjetCorba-DNS/GestionNomsDomaine.idl
* vendredi 16 décembre 2016 18 h 25 CET
*/

public interface ProprietaireforRegistrarOperations 
{

  // notifie le client qu'un nom de domaine est sur le point d'expirer
  void DomainNameExpiration (String DomainName, String DateExpiration);
} // interface ProprietaireforRegistrarOperations
