package ProjetCorbaDNS.Proprietaire;

/**
* ProjetCorbaDNS/Proprietaire/ProprietaireforRegistrarHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/Users/Manavai/workspace/ProjetCorba-DNS/GestionNomsDomaine.idl
* vendredi 16 décembre 2016 18 h 25 CET
*/

public final class ProprietaireforRegistrarHolder implements org.omg.CORBA.portable.Streamable
{
  public ProjetCorbaDNS.Proprietaire.ProprietaireforRegistrar value = null;

  public ProprietaireforRegistrarHolder ()
  {
  }

  public ProprietaireforRegistrarHolder (ProjetCorbaDNS.Proprietaire.ProprietaireforRegistrar initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ProjetCorbaDNS.Proprietaire.ProprietaireforRegistrarHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ProjetCorbaDNS.Proprietaire.ProprietaireforRegistrarHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ProjetCorbaDNS.Proprietaire.ProprietaireforRegistrarHelper.type ();
  }

}
