package ProjetCorbaDNS.Registrar;


/**
* ProjetCorbaDNS/Registrar/_RegistrarForClientStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/Users/Manavai/workspace/ProjetCorba-DNS/GestionNomsDomaine.idl
* vendredi 16 d�cembre 2016 18 h 25 CET
*/

public class _RegistrarForClientStub extends org.omg.CORBA.portable.ObjectImpl implements ProjetCorbaDNS.Registrar.RegistrarForClient
{


  // demander à un registrar si un nom de domaine est libre pour location
  public boolean DomainNameRentingRequest (String DomainNameToRent)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("DomainNameRentingRequest", true);
                ProjetCorbaDNS.DomainNameHelper.write ($out, DomainNameToRent);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return DomainNameRentingRequest (DomainNameToRent        );
            } finally {
                _releaseReply ($in);
            }
  } // DomainNameRentingRequest


  // demander à un registrar de louer un nom de domaine
  public ProjetCorbaDNS.ClientID rentDomain (String DomainNameToRent, ProjetCorbaDNS.UserInformations userInformations)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("rentDomain", true);
                ProjetCorbaDNS.DomainNameHelper.write ($out, DomainNameToRent);
                ProjetCorbaDNS.UserInformationsHelper.write ($out, userInformations);
                $in = _invoke ($out);
                ProjetCorbaDNS.ClientID $result = ProjetCorbaDNS.ClientIDHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return rentDomain (DomainNameToRent, userInformations        );
            } finally {
                _releaseReply ($in);
            }
  } // rentDomain

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ProjetCorbaDNS/Registrar/RegistrarForClient:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _RegistrarForClientStub
