package ProjetCorbaDNS.Registrar;


/**
* ProjetCorbaDNS/Registrar/RegistrarForClientOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/Users/Manavai/workspace/ProjetCorba-DNS/GestionNomsDomaine.idl
* vendredi 16 d�cembre 2016 18 h 25 CET
*/

public interface RegistrarForClientOperations 
{

  // demander à un registrar si un nom de domaine est libre pour location
  boolean DomainNameRentingRequest (String DomainNameToRent);

  // demander à un registrar de louer un nom de domaine
  ProjetCorbaDNS.ClientID rentDomain (String DomainNameToRent, ProjetCorbaDNS.UserInformations userInformations);
} // interface RegistrarForClientOperations
