package ProjetCorbaDNS.Registrar;

/**
* ProjetCorbaDNS/Registrar/RegistrarForClientHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/Users/Manavai/workspace/ProjetCorba-DNS/GestionNomsDomaine.idl
* vendredi 16 décembre 2016 18 h 25 CET
*/

public final class RegistrarForClientHolder implements org.omg.CORBA.portable.Streamable
{
  public ProjetCorbaDNS.Registrar.RegistrarForClient value = null;

  public RegistrarForClientHolder ()
  {
  }

  public RegistrarForClientHolder (ProjetCorbaDNS.Registrar.RegistrarForClient initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ProjetCorbaDNS.Registrar.RegistrarForClientHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ProjetCorbaDNS.Registrar.RegistrarForClientHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ProjetCorbaDNS.Registrar.RegistrarForClientHelper.type ();
  }

}
