package ProjetCorbaDNS.Registrar;


/**
* ProjetCorbaDNS/Registrar/RegistrarForProprietaireOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/Users/Manavai/workspace/ProjetCorba-DNS/GestionNomsDomaine.idl
* vendredi 16 d�cembre 2016 18 h 25 CET
*/

public interface RegistrarForProprietaireOperations 
{

  // Configurer les paramètres d'un nom de domaine
  boolean AddParameter (String ParameterType, String DomainName, String ParameterValue);
  boolean ModifyParameter (String DomainName, String ParameterType, String ParameterValue);
  ProjetCorbaDNS.DomainNameParameters GetDomainParameters (String DomainName);

  // transferer un nom de domaine vers un nouveau propriétaire
  boolean DomainNameRenewRequest (String DomainNameToRenew);
  boolean renewDomain (String DomainName, ProjetCorbaDNS.UserInformations UserInformations);
  boolean ChangeOwnerRequest (String DomainName, ProjetCorbaDNS.UserInformations NewOwner);

  // changer de registrar
  ProjetCorbaDNS.UserInformations changeRegistrarRequest (ProjetCorbaDNS.DomainNameInformations DomainNameInformations, ProjetCorbaDNS.UserInformations UserInformations);
  String changeRegistrarTransactionRequest (ProjetCorbaDNS.DomainNameInformations DomainNameInformations);
  boolean changeRegistrarTransactionBegin (String DNTransactionID);
  boolean changeRegistrarTransactionCommit (String DNTransactionID);
  boolean changeRegistrarTransactionRollback (String DNTransactionID);
  ProjetCorbaDNS.UserInformations changeRegistrarValidateTransaction (String DNTransactionID);
} // interface RegistrarForProprietaireOperations
