package ProjetCorbaDNS.Banque;


/**
* ProjetCorbaDNS/Banque/BanqueForPublicOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/Users/Manavai/workspace/ProjetCorba-DNS/GestionNomsDomaine.idl
* vendredi 16 d�cembre 2016 18 h 25 CET
*/


/* Interface utilisé par les registrar pour demander un transfert d'argent
		lors d'un location, d'un renouvellement de domaine, ou bien d'un changement
		de Registrar par un propriétaire d'un DN. 
		
		*/
public interface BanqueForPublicOperations 
{

  // méthode permettant d'ordonner un Transfert d'argent
  String TransferMoney (String TransfertFromRIB, String TransfertToRIB, int SUM);

  // méthode permettant de vérifier le status d'un transfert
  String CheckTransfertStatus (String transfertID);
} // interface BanqueForPublicOperations
