package ProjetCorbaDNS.Banque;


/**
* ProjetCorbaDNS/Banque/BanqueForPublicHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/Users/Manavai/workspace/ProjetCorba-DNS/GestionNomsDomaine.idl
* vendredi 16 d�cembre 2016 18 h 25 CET
*/


/* Interface utilisé par les registrar pour demander un transfert d'argent
		lors d'un location, d'un renouvellement de domaine, ou bien d'un changement
		de Registrar par un propriétaire d'un DN. 
		
		*/
abstract public class BanqueForPublicHelper
{
  private static String  _id = "IDL:ProjetCorbaDNS/Banque/BanqueForPublic:1.0";

  public static void insert (org.omg.CORBA.Any a, ProjetCorbaDNS.Banque.BanqueForPublic that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ProjetCorbaDNS.Banque.BanqueForPublic extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (ProjetCorbaDNS.Banque.BanqueForPublicHelper.id (), "BanqueForPublic");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ProjetCorbaDNS.Banque.BanqueForPublic read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_BanqueForPublicStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ProjetCorbaDNS.Banque.BanqueForPublic value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static ProjetCorbaDNS.Banque.BanqueForPublic narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ProjetCorbaDNS.Banque.BanqueForPublic)
      return (ProjetCorbaDNS.Banque.BanqueForPublic)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ProjetCorbaDNS.Banque._BanqueForPublicStub stub = new ProjetCorbaDNS.Banque._BanqueForPublicStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static ProjetCorbaDNS.Banque.BanqueForPublic unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ProjetCorbaDNS.Banque.BanqueForPublic)
      return (ProjetCorbaDNS.Banque.BanqueForPublic)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ProjetCorbaDNS.Banque._BanqueForPublicStub stub = new ProjetCorbaDNS.Banque._BanqueForPublicStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
